### PR TITLE
feat(hive-graphql): upload helm chart

### PR DESCRIPTION
**Pull request by hermeto**
## What does this PR do?

Uploads helm chart based on https://github.com/diabolocom/graphql-hive

## Type of change

This pull request is a
- [x] Feature
- [ ] Bugfix
- [ ] Enhancement

Which introduces
- [ ] Breaking changes
- [x] Non-breaking changes

### CODE REVIEW

**Review by greguintow — COMMENTED** [review]
why it's being based on a unofficial one instead of https://github.com/kamilkisiela/graphql-hive?

**Comment by hermeto** [comment]
> why it's being based on a unofficial one instead of https://github.com/kamilkisiela/graphql-hive?

The official repository does not include any helm configuration available, only manifests for docker-compose. This repository that I am using is already very complete, with all the necessary dependencies.

**Review by greguintow — APPROVED** [review]
LGTM

**Review by longyarnz — APPROVED** [review]

**Comment by sudotong** [comment]
@longyarnz would these changes still be needed?

**Pull request closed without merging**
